rdsTags:
  tagName: "Environment"
  tagValue: "Production"

allowedIAMUsers:
  - "user1"
  - "user2"
  - "user3"

envTag:
  Test:
    environment: "qa"
  Stage:
    environment: "staging"

caching:
  enabled: true
  duration: 1d

checkIAMPermissions: true
